name: Local Action
on:
  push:
  workflow_run:
    workflows: 
      - "Build Action"
    types:
      - completed

permissions:
  contents: read

jobs:
  test-action:
    name: Test Action Locally
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./
        with:
          is_local: true

